// src/app/layout.tsx
import ClientLayout from './ClientLayout'; // Se já estiver usando ClientLayout
import Footer from './footer/page'; // Importe o componente Footer

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>
          {children}
        </ClientLayout>
        <Footer />
      </body>
    </html>
  );
}
